# Create a GitHub Actions workflow that triggers a build in Jenkins and deploys
# the build artifact to an AWS environment using AWS CodePipeline.

name: Lesson 9/Task 1

on: workflow_dispatch

jobs:
  trigger-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build
        uses: appleboy/jenkins-action@v0.0.4
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: 'my-jenkins-job-name'

      - name: Wait for Build to Complete
        uses: jenkinsci/wait-for-build-action@v1
        with:
          job-url: ${{ secrets.JENKINS_JOB_URL }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          user: ${{ secrets.JENKINS_USER }}

  deploy-to-aws:
    needs: trigger-jenkins-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Deploy Build Artifact to AWS CodePipeline
        run: aws codepipeline start-pipeline-execution --name my-codepipeline-name