# Set up a conditional trigger to run a deployment job only on the main branch.

name: Lesson 2/ Task 3

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == "refs/heads/main"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy Code
        run: echo "Deploying..."