# Modify the workflow to include environment variables and a secret.

name: Lesson 3/Task 2

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 16
      
      - name: Build
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}