# Configure a GitHub Actions workflow with restricted permissions, secure secrets management,
# and code scanning. Ensure that the workflow adheres to best security practices.

name: Lesson 7/Task 1

on: workflow_dispatch

permissions:
  contents: read
  deployments: write

jobs:
  code-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        run: codeql database analyze --format=sarif -o codeql-report.sarif

      - name: Upload Code Scanning Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql-report.sarif

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: code-scan
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy Application
        run: npm run deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}