# Implement caching for npm dependencies in the workflow to optimize execution time.

name: Lesson 2/Task 1

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: /.npm
          key: npm-cache=${{ hashFiles('**/package-lock.json') }}
          restore-keys:
            npm-cache-

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 16
      
      - name: Install Dependencies
        run: npm install