# Implement error handling and retry logic in a workflow that deploys an application.

name: Lesson 6/Task 1

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        continue-on-error: true

      - name: Deploy Application
        run: |
          for i in {1..3}; do
            if npm run deploy; then
              echo "Deployment successful"
              exit 0
            else
              echo "Deployment failed, retrying in 10 seconds..."
              sleep 10
            fi
          done
          echo "Deployment failed!"
          exit 1
        timeout-minutes: 10