name: Test Reusable Workflow

on: 
  workflow_dispatch

jobs:
  call_workflow: 
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml